######################################################################
# Automatically generated by qmake (3.0) Tue Aug 8 14:19:53 2017
######################################################################

TEMPLATE = app
TARGET = Alien
INCLUDEPATH += . /opt/local/include

QT += widgets opengl gui

LIBS += -lglut -lGLU

# Input
HEADERS += Image.h AlienWidget.h AlienWindow.h
SOURCES += AlienMain.cpp \
           AlienWidget.cpp \
           AlienWindow.cpp \
           Image.cpp
